company/urls.py
from django.urls import path 

from . import views

app_name = "company"
urlpatterns = [
    path("", views.company_home, name="company_home"),
    path("register/", views.company_register, name="company_register"),
    path("login/", views.company_login, name="company_login"),
    path("logout/", views.logout_request, name= "logout"),
    path("changepassword/", views.change_password, name="change_password"),
    path("add_employee/", views.add_employee, name="add_employee"),
    path("employee_report/", views.employee_report, name="employee_report"),
    path("contact/", views.contact, name="contact")
    
    
]   

payroll/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('company/', include("company.urls")),



]

company/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class CompanyModel(models.Model):
    name = models.CharField(max_length = 222)
    username = models.CharField(max_length= 220)
    email = models.EmailField()
    password = models.CharField(max_length = 222)
    

    def __str__(self):
        return (f"Id : {self.id} UserName : {self.username} Name: {self.__name__} Email: {self.email} Password: {self.password}")


class AddEmployee(models.Model):
    name = models.CharField(max_length=122, help_text=u"Name")
    address = models.CharField(max_length=322)
    city = models.CharField(max_length=123)
    postalcode = models.IntegerField( )
    modile = models.IntegerField()
    signation = models.CharField(max_length= 44)
    branch = models.CharField(max_length=44)
    rank = models.CharField(max_length=10)
    basic_pay = models.IntegerField()
    bank_account = models.CharField(max_length=44)
    email = models.EmailField( max_length= 254)
    
    def __str__(self):
        return ( f"Name : { self.name } Signation :  {self.signation} Branch : {self.branch}  rank   {self.rank}")
class ContactUs(models.Model):

    first_name = models.CharField(max_length=63)
    last_name = models.CharField(max_length=63)
    mobile = models.IntegerField()
    email = models.EmailField()
    urls = models.URLField()
    message = models.TextField(max_length=1200)
    def __str__(self):
        return (f"Name : {self.first_name} Email : {self.email}")

company/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate,logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper

from . models import CompanyModel, AddEmployee
from . form import AddEmployeeForm,ContactForm
from . register import NewUserForm
# from .forms import NewUserForm

# Create your views here.


def company_home(request):
    diction = {"title": "welcome ",
            "employees": AddEmployee.objects.count()
               }
    return render(request, "company/company_home.html", context=diction)
###################################################

def add_employee(request, ):
    
    if request.method == "POST":
        form = AddEmployeeForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect("company:employee_report")
        else:
            
            return render(request, "company/add_employee.html",{"form": form})
        
    diction = {
        "title": "Add Employee",
        "form": AddEmployeeForm()
    }
    return render(request, "company/add_employee.html", context= diction)

#####################################################
# Employee Report
def employee_report(request):
    if "employee" not in request.session:
        request.session["employee"] = []
    return render(request, "company/employee_report.html",{"title": "Employee Report", "employees": AddEmployee.objects.all() })


####################################################
# company Rigster request 
def company_register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.error(request, "Registration Successful. ")

            return redirect("company:company_home")
        messages.error(request, "Unsuccessful registration. indalid information. ")
        
    diction = {"title": "Register ",
               "Company_register": NewUserForm(),
               }    
    return render(request, "company/company_register.html", context=diction)
######################################################
# company login request
def company_login(request):

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username= username,password= password)
            if user is not None:
                login(request,user)
                messages.info(request,f"you are now logged in as {username}")
                return redirect("company:company_home")
            else:
                messages.info(request,"Invalid username or password")

    diction = {"title": "Login",
               "companyform": AuthenticationForm()}
    
    return render(request, "company/company_login.html", context=diction)
######################################################
# logout request 
def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.") 
    return redirect("index")
###################################################
# change password _____________________
def change_password(request):

    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect("company:company_login")
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    diction = {
        "title": "Change password",
        "change_password_form": form,
    }
    return render(request, "company/change_password.html", context=diction)
########################################## Contact page view
def contact(request):
    if request.method=="POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
    diction = {
        "title": "Contact",
        "contact_form": ContactForm()
    }
    return render(request, "contact.html", context=diction)

payroll/views.py
from django.shortcuts import render

def index(request):
    diction={"title":"Welcome Our Payroll System"}
    return render(request, 'index.html',context=diction)
# def logout_request(request):
#     logout(request)
# 	messages.info(request, "You have successfully logged out.") 
# 	return redirect("company:com")

templates/account_layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/login_form.css' %}">
</head>
<body>

<section class="header-section">
    <center><h1><span class="material-icons">
        paid</span>P<small>AYROLL</small> S<small>YSTEM</small></h1></center>
</section>
<section class="body-section">

    <div class="mainbody">
        <center><P id="page_title">{{title}}</P></center>
        <div class="container">
            {% block body %}

            {% endblock %}
        </div>
    </div>
</section>


    <section class="footer-section">
    <center><P id="copyright">Copyright 2021@Payroll System</P></center>
</section>
</body>
</html>

templates/company/add_employee.html
{% extends 'company/company_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %} 

<div class="contain">
    <div id="employee">
    <form action="#" method="post">
        {% csrf_token %}
        <div class="input"><b> Name: </b>{{ form.name }}</div>
        <div class="input"><b>Email: </b>{{ form.email}}</div>
        <div class="input"><b> Address: </b>{{ form.address }}</div>
        <div class="input"><b>City: </b>{{ form.city }}</div>
        <div class="input"><b>Postal Code:</b> {{ form.postalcode }}</div>
        <div class="input"><b>Modile: </b>{{ form.modile }}</div>
        <div class="input"><b>Signation: </b>{{ form.signation }}</div>
        <div class="input"><b>Branch: </b>{{ form.branch }}</div>
        <div class="input"><b>Rank: </b>{{ form.rank }}</div>
        <div class="input"><b>Basic Pay:</b> {{ form.basic_pay }}</div>
        <div class="input"><b>Bank Account: </b>{{ form.bank_account}}</div>


        
        <input type="submit" value= "Add Employee">
    </form>
</div>
</div>
{% endblock %}

templates/company/change_password.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %} 

<div class="login_form"><center>
        <form action="#" method="POST">
                {% csrf_token %}
                {{change_password_form|crispy}}
                <input type="submit" value="Save Change">
                <a href="{% url 'company:company_register' %}">Log In</a>

        </form>
</center>
</div>

{% endblock %}

templates/company/company_home.html
{% extends 'company/company_layout.html' %}
{% load static %}
{% block body %} 

<div class="contain"><center>
        <div class="box_1"><h1>Employee</h1><b>{{ employees }}</b></div>
        <div class="box_1"><h1>Active</h1><b>1</b></div>
        <div class="box_1"><h1>Deactive</h1><b>1</b></div>
        <div class="box_1"><h1>New Leave</h1><b>0</b></div>
        <div class="box_1"><h1>Approved</h1><b>1</b></div>
        <div class="box_1"><h1>Rejected</h1><b>1</b></div>
</center>
</div>

{% endblock %}

templates/company/company_layout.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">   
    <link rel="stylesheet" href="{% static 'css/login_form.css' %}">
    <title>{{title}}</title>
</head>
<body>

<section class="header-section">
    <center><h1><span class="material-icons">
        paid</span>P<small>AYROLL</small> S<small>YSTEM</small></h1></center>
</section>
<section class="body-section">
    <div class="menu">
        <center><ul>
            <li><a href="{% url 'index' %}">HOME</a></li>
            <!-- <li><a href="#">ADD CLASS</a></li> -->
            <li><a href="{% url 'company:add_employee' %}">ADD Employee</a></li>
            <li><a href="{% url 'company:employee_report' %}">Employee Report</a></li>
            <li><a href="#">Leave</a></li>
            <li><a href="#">Salary</a></li>
            <li><a href="#">Salary Report</a></li>
            <li><a href="#">Year wise Report</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="{% url 'company:change_password' %}">Change Password</a></li>
            <li><a href="{% url 'company:logout' %}">LogOut</a></li>
        </ul></center>
    </div>
    <div class="mainbody">
        <center><P id="page_title">{{title}}</P></center>
        <div class="container">
            {% block body %}

            {% endblock %}
        </div>
    </div>
</section>

templates/company/company_login.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %} 

<div class="login_form"><center>
        <form action="#" method="POST">
                {% csrf_token %}
                {{companyform|crispy}}
                <input type="submit" value="Log in">
                <a href="{% url 'company:company_register' %}">Register</a>

        </form>
</center>
</div>

{% endblock %}

templates/company/company_register.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %} 
<div class="login_form">
    <center>
    <form action="#" method="post">
        {% csrf_token %}
            {{Company_register|crispy}}
            <input type="submit" value="Register">
            <a href="{% url 'company:company_login' %}">Login</a>

    </form>
</center>
</div>
{% endblock %}

templates/company/employee_report.html
{% extends 'company/company_layout.html' %}
{% load static %}
{% block body %} 
<table class="table">
    <tr>
        <th>Name :</th>
        <th>Email :</th>
        <th>Mobile :</th>
        <th>Signation :</th>
        <th>Branch :</th>
        <th>Rank :</th>
    </tr>
    {% for employee in employees %}
    <tr>
        <td>{{employee.name}}</td>
        <td>{{employee.email}}</td>
        <td>{{employee.modile}}</td>
        <td>{{employee.signation}}</td>
        <td>{{employee.branch}}</td>
        <td>{{employee.rank}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

templates/contact.html
{% extends 'layout.html' %}
{% block body%}
<div class="contact">
<div class="contact_box c-box">
    <div class="contact_head">
        <h1>Reach out to us</h1>
        <p>We would love to hear from you</p>
    </div>
    <div class="contact">
        <li><span class="material-icons">my_location</span><b>District Education Office Road, Magura </b></li>
        <li><span  class="material-icons">call</span><a href="tel:+880123465780">+880123465780</a></li>
        <li><span  class="material-icons">email</span><a href="mailto:payroll5398@gmail.com">payroll5398@gmail.com</a></li>
    </div>
</div>

<form action="" method="post" class="contact-form c-box">
    First Name : 
    <div class="c-in-box">{{contact_form.first_name}}</div>
    Last Name : 
    <div class="c-in-box">{{contact_form.last_name}}</div>
    Urls : 
    <div class="c-in-box">{{contact_form.urls}}</div>
    Mobile : 
    <div class="c-in-box">{{contact_form.mobile}}</div>
    Email : 
    <div class="c-in-box">{{contact_form.email}}</div>
    Message : 
    <div class="c-in-box">{{contact_form.message}}</div>

    <input type="submit" name="" id="Send" value="Send">
</form>
</div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% load static %}
{% block body %} 


<div class="mainsection">
<div id="block-1" style="background-image: url({% static 'images/background.jpg' %});"><div class="contner">
    <div class="text">
<!-- <h1>Welcome To Our Website</h1> -->
<h1>Payroll Services for Small Businesses</h1>
<p>
    Our payroll technology and 24/7 service platform makes it simple to:
    <b class="li">Run payroll online</b>
    <b class="li">Automatically calculate, pay, and file taxes</b>
    <b class="li">Allow your employees to initiate self-service actions</b>
</p>
<button type="menu"><a href="{% url 'company:company_register' %}">Join Now</a></button>
</div>
</div></div>
<div id="block-2"><div class="contner">
<h1>What You Get with Paychex Payroll Services for Small Businesses</h1>
<ul>
<li>Flexible payroll processing online from desktop and mobile, or you can call your payroll specialist</li>
<li>Ability to pay different types of workers – salaried, hourly, contract</li>
<li>Automatic payroll tax administration</li>
<li>Payroll dashboard with configurable views</li>
<li>New-hire reporting to government agencies</li>
<li>Online employee self-service</li>
</ul>
<ol >
<li>Direct deposit, paycards, paper checks, online tip sharing, and on-demand access to earned wages</li>
<li>Free mobile app for you and your employees</li>
<li>HR analytics and events calendar</li>
<li>Labor compliance poster kit</li>
<li>Garnishment payments</li>
<li>Robust reporting and analytics for insights into your payroll and HR data</li>
<li>24/7 customer service and technical support</li>

</ol>
</div></div>
<div id="block-3"><div class="contner"></div></div>
<div id="block-4"><div class="contner"></div></div>
<div id="block-5"><div class="contner"></div></div>

</div>


{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/login_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>

<!-- <section class="header-section clear">
    <center><h1><span class="material-icons">
        paid</span>P<small>AYROLL</small> S<small>YSTEM</small></h1></center>
</section>



        <div id="page_title_bar">
        <a href="{% url 'index' %}"><span class="material-icons">
            home
            </span></a>
        <center><P id="page_title">{{title}}</P></center>
    </div> -->
{% block navbar %} {% include 'navbar.html' %}{% endblock %}


<section class="body-section clear">
    <div class="mainbody ">
            {% block body %}

            {% endblock %}
    </div>
</section>


    <section class="footer-section clear">

    <table class="contain-header">
        <tr>
            <th><h1>Contact Us</h1></th>
            <th><h1>Company</h1></th>
            <th><h1>Company</h1></th>
            <th><h1>Resources</h1></th>
        </tr>
    </table>
        <div class="footer_box">
            <div class="content">
            <li><a href="#">SMS SAGE TO 4352</a></li>
            <li><a href="#">+8801809123123</a></li>
            <li><a href="#">payroll980@gmail.com</a></li>
            <li><a href="#">www.softwaremark.com</a></li>
            </div>
        </div>
        <div class="footer_box">
            <div class="content">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">Partner Program</a></li>
            </div>
        </div>
        <div class="footer_box">
            <div class="content">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">Partner Program</a></li>
            </div>
        </div>
        <div class="footer_box">
            <div class="content">
                <li><a href="#">FAQs</a></li>

            </div>
        </div>
  
    <center><P id="copyright">Copyright 2021@Payroll System</P></center>
</section>
</body>
</html>

templates/navbar.html
{% block navbar %}
<div class="naigation clear">
<div class="navimenu">
    <div class="unouder colam">
        <Ul>
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Our Serves</a></li>
            <li><a href="#">Our Patnar</a></li>
            <li><a href="{% url 'company:contact' %}">Contact Us</a></li>
            <li><a href="#">We Provide sirves</a></li>
        </Ul>
    </div>
    <div class="ouder colam">
        <ol >
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'company:company_home' %}"> {{user.username}}</a>/ 
            <a href="{% url 'company:logout' %}">LogOut</a>
            </li>
        
            {%else%}
                    <li><a href="{% url 'company:company_login' %}">Sign In</a></li>
            {%endif%}
        </ol>
    </div>
</div>
</div>
{% endblock %}